on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.11.x', 'stable']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
        cache: true
    - name: Test
      run: go test -race -v ./...
