name: Update release

on:
  workflow_run:
    workflows: ["goreleaser"]
    types:
      - completed

jobs:
  download:
    name: Update proxied module version
    runs-on: ubuntu-latest
    steps:
    - name: Pull new module version
      uses: andrewslotin/go-proxy-pull-action@master
